dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.2
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.2'
networks:
  rinkeby:
    verify: true
  goerli: 
    verify: true
  sepolia: 
    verify: true
  development:
    verify: false
wallets: 
  from_key: ${PRIVATE_KEY}
